### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by PharrellWANG** [JiahuiYu/generative_inpainting#144]
I have tried to inpaint images of resolution 1920x1080 using CPU only. But the inpainting consumes so much memory, nearly 24GB. May I ask why is it? Is it possible to come up with some fixations? It is a problem when trying to inpaint a single image consumes 24 GB memory.

FYI, attached are my mask of resolution 1920x1080.
![rec_mask_poc_1](https://user-images.githubusercontent.com/22740944/46128827-6105f300-c267-11e8-8604-49eea91920a9.png)

Also, when I try to inpaint image of resolution 2560x1600, lots of swap memory has been consumed, nearly 60GB. And eventually the process got killed, so inpainting didn't make it.
<img width="853" alt="screenshot 2018-09-27 at 4 25 06 pm" src="https://user-images.githubusercontent.com/22740944/46134227-f8257780-c274-11e8-86c5-b6e6df29a8e7.png">
<img width="226" alt="screenshot 2018-09-27 at 4 24 58 pm" src="https://user-images.githubusercontent.com/22740944/46134229-fa87d180-c274-11e8-9cf4-16ae4240c751.png">

Below is my mask of size 2560x1600:
![rec_mask_poc_4](https://user-images.githubusercontent.com/22740944/46134328-302cba80-c275-11e8-9a18-606d4f4ba7ad.png)

**Comment by JiahuiYu** [comment]
@PharrellWANG Hi you are right. Because our network tries to find similar information over the whole image. Instead of using local convolutions along, we are using non-local contextual attention block.

It will be very clear why memory is required during inference on large images, if one can understand Figure 3 in our paper.

In your case, there are solutions to reduce memory, by cropping patches and individually filling holes.
