### ISSUE TITLE
About my test

### ISSUE THREAD

**Issue by JinMengKang** [JiahuiYu/generative_inpainting#171]
Dear author, thank you for your excellent work.
I trained the model with nearly 30,000 pictures. A week later, when I tested it, I found my test output very strange. I used DeepFillv2 to train the model.
I hope you can help me out, thank you very much.
![47328692-8fc78b80-d6a4-11e8-85a0-19c2c1258677](https://user-images.githubusercontent.com/31871033/47830694-fac14280-ddc7-11e8-8956-d95e332ec8f7.png)

**Comment by JiahuiYu** [comment]
@JinMengKang Basically that means the training of GAN is failed. It can be caused by many problems, for examples, some hyper-parameters. I think the first step to debug is to set extremely high pixel-wise reconstruction loss. For example, set to 10 in these two [lines](https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint.yml#L13-L14) and then see if the predicted colors are correct or not (of course the results will be blur but you can at least debug if the problem is the hyper-parameter settings of GAN loss balancing). 

Another suggestion is to track the training progress on the tensorboard in time, so that you can early-stop  training if results are very bad.

**Comment by JinMengKang** [comment]
I'm sorry to bother you again.
I modified these parameters according to your suggestion, but I tried some parameters but this happened: every time after training for a while, a small piece of failed patch will appear. can you tell me what the reason is?

**Comment by JiahuiYu** [comment]
I don't know the reason in your case. You probably need to find it out yourself.
