### ISSUE TITLE
Question about discriminator in deepfill2

### ISSUE THREAD

**Issue by cmyyy** [JiahuiYu/generative_inpainting#232]
Hello,@JiahuiYu.
You said all layer in discriminator apply like below:
x = leaky_relu(conv2d_spectral_norm(x))
But in original patchGAN as well as discriminator in SNGAN,there is no activation in last layer. 
Why you add an activation in last layer?

**Comment by JiahuiYu** [comment]
Hi,

Several people have asked this question before. A simple answer is that you can remove the last activation and have a test. I add it because leakyReLU is piecewise linear, and should not make much difference compared with linear activation (I.e., no activation). I have not yet tested whether this will help the performance or not. In practice, the discriminator works fine.
