### ISSUE TITLE
Sorry to bother u again.

### ISSUE THREAD

**Issue by knowtheworld** [JiahuiYu/generative_inpainting#255]
My checkpoint file doesn't have `.txt`.But it still say:
`Couldn't find 'checkpoint' file or checkpoints in given directory`
My os is Windows8.1,doesn't this matters?And I run test.py with only cpu.
Thanks for your reading!

**Comment by bangawayoo** [comment]
Hello, I had the same problem. 

Assuming you are having the same problem,
the solution is to actually change the extension of the 'checkpoint.txt', instead of changing the name only. You may need to change the setting on your machine first. Please take a look here:
https://www.thewindowsclub.com/show-file-extensions-in-windows

Hope this helps!

**Comment by knowtheworld** [comment]
> Hello, I had the same problem.
> 
> Assuming you are having the same problem,
> the solution is to actually change the extension of the 'checkpoint.txt', instead of changing the name only. You may need to change the setting on your machine first. Please take a look here:
> https://www.thewindowsclub.com/show-file-extensions-in-windows
> 
> Hope this helps!

Problem solved!Thanks so much!
But I can't get a fine results with my pictures(some weird results).I want to know what changes should I make to settings.

**Comment by JiahuiYu** [comment]
Make sure you are using correct model for correct dataset. There are a few questions in the closed issue. Please read as well.

You don’t need to open new issue. Reply here if you have more question.

Thank @bangawayoo for your help!
