### ISSUE TITLE
The result about model of release_places2_256

### ISSUE THREAD

**Issue by gunerhui** [JiahuiYu/generative_inpainting#282]
I find the result from model of release_places2_256 is diffrent from your papper
![sunset_input](https://user-images.githubusercontent.com/41320813/60233269-256d8780-98d2-11e9-8fdb-92129e2e3da1.png)
 
![output](https://user-images.githubusercontent.com/41320813/60233282-35856700-98d2-11e9-8492-afa1d0b5dea9.png)

in your papper
![image](https://user-images.githubusercontent.com/41320813/60233329-6fef0400-98d2-11e9-9e77-09fb99e87672.png)

is the model   " release_places2_256"  in your papper?

I test some other images ,some results are like this has boundary traces. How should I improve?

**Comment by JiahuiYu** [comment]
Yes the released model can reproduce our results in the paper. Thus the way you use our model is wrong. Have you exactly followed our README?

**Comment by yangyu12** [comment]
Hi @JiahuiYu ,
   Maybe a strange question. I use the pretrained model `release_places2_256_deepfill_v2`, trying to reproducing the demo inpainting provided in the folder `examples/places2`. However, I got a quite blurred inpainted image, as shown below.
My result
![image](https://user-images.githubusercontent.com/17905452/74247159-8faa2f80-4cdd-11ea-86bc-e6c6574ce523.png)
Your result 
![image](https://user-images.githubusercontent.com/17905452/74247215-a51f5980-4cdd-11ea-86b3-eace229b74ce.png)

It seems that the refinement stage doesn't work in my case. It worth noting that I use my [re-implementation](https://github.com/yangyu12/deepfill_v2.pytorch) with PyTorch because I hate tensorflow. Do you have any idea about how it happens?

I know it is tricky to answer my question but could you please give me some speculative thoughts? 

Thank you very much!

**Comment by JiahuiYu** [comment]
@yangyu12  I guess your model is not well-trained. This artifact is common when my model is not converged as well.

**Comment by yangyu12** [comment]
@JiahuiYu Thanks for the reply. In fact, I didn't train the model yet. I use the **pretrained model** ([Places2](https://drive.google.com/drive/folders/1y7Irxm3HSHGvp546hZdAZwuNmhLUVcjO)) given in README and try to reproduce the demo results. I suppose it should be well-trained. Could you please help to check if it is the well-trained one?

Thanks!

**Comment by JiahuiYu** [comment]
> It worth noting that I use my re-implementation with PyTorch because I hate tensorflow.

So you just convert the weights? Then it should be a tensorflow-pytorch question instead of an Inpainting question.

**Comment by yangyu12** [comment]
@JiahuiYu Oh, you mean that it is not trivial to convert the weights? Then I think I still need to train the model.
