### ISSUE TITLE
No indication for training using multi - GPU- reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#350]
Hi @JiahuiYu 

Thanks for your prompt responses,

I have done the multigpu training based on you are suggestion using deepfill2 . (issue #349 )
Now, I am currently working on deepfill1 not deepfill2. 
You have suggested to use deepfill2 of multigpu in deepfill1.

It is working fine now. gpu's id : [0,1,5]

![WeChat Image_20191112113455](https://user-images.githubusercontent.com/57310377/68639735-7d82ee80-0540-11ea-9787-070f93430a51.png)

**But Now, started the another issue that is: (issue #323)** 

![WeChat Image_20191112113600](https://user-images.githubusercontent.com/57310377/68639771-a1463480-0540-11ea-809e-56543edc12cf.png)

I have read the issue #323. still the issue is open. 
Hence, kindly let me know, how to find the model is training and when it will be complete.

Thanks in advance

**Comment by JiahuiYu** [comment]
https://github.com/JiahuiYu/neuralgym/commit/88292adb524186693a32404c0cfdc790426ea441

**Comment by Adhiyaman-Manickam** [comment]
Thanks @JiahuiYu 

But using multi gpu for training speed is lesser than single gpu. 
In my case for single gpu for training speed is 0.43 batches/sec but now using multi gpu - 0.39 batches/sec.

![WeChat Image_20191113111255](https://user-images.githubusercontent.com/57310377/68730360-78d53d80-0607-11ea-8ad6-2d2d8bb985b9.png)


I am understanding about this issues.

Kindly let me know, where i made a mistake.

**Comment by JiahuiYu** [comment]
@Adhiyaman-Manickam Hey, now your batch size is your original batch size x number of GPUs.

**Comment by Adhiyaman-Manickam** [comment]
Thanks @JiahuiYu . Sorry for the disturbance. 
Eventhough, it takes more time to complete the train epoch.

**Comment by pancookie** [comment]
> Thanks @JiahuiYu . Sorry for the disturbance.
> Eventhough, it takes more time to complete the train epoch.

Hey Adhiyaman, 
I was confused by the same issue. Then I figured out the explanation by reading the codes thoroughly. 
the `train_ops_and_losses()` function in `ng/train/multigpu_trainer.py` actually runs [number of gpus] batches, however, in the training process it is still counted as "one step" while with your max iterations unmodified, you are practically running your model [number of gpus] * max_iters times. 
To modify it to let the batches/sec showing properly I think you can set `step += num_gpus` rather than `step += 1`. Be careful about other callbacks since train() in ng/train/trainer.py is shared by 2ndaryTrainer, multigpuTrainer and probably other callbacks..

Regards,
Yang
