### ISSUE TITLE
how to train single channel images? like[256, 256, 1]

### ISSUE THREAD

**Issue by qingshuiruoshan** [JiahuiYu/generative_inpainting#359]
Hello @JiahuiYu 
I'm sorry to bother you, but I have a problem need to solve. I want to train the images of a single channel now, like[256, 256, 1], but I don't know what should be modified to meet my needs. I have seen the solutions to some related problems before, but this problem still hasn't been solved. Could you please give me some detailed guidance on what needs to be modified? Thanks!

**Comment by JiahuiYu** [comment]
I guess you can simply read the image as RGB and dropout the GB channel as a single channel image in computation graph, if you do not have time to implement.

**Comment by qingshuiruoshan** [comment]
Thanks for your suggestion. I think the method you said is to expand the single-channel image into three-channel images with the same values for training? I feel this is a good solution to my problem!

**Comment by LP429** [comment]
Hi, @qingshuiruoshan!
How is your work going? When I do this work like yours, the program has such a problem：
ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible
So do you have this situation and how did you solve it?
Thank you!!

**Comment by qingshuiruoshan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,
        I haven't solved this problem yet. But maybe you can refer to the following two ways: the first is  that you can refer to https://github.com/konstantg/dem-fill. Second, you can train the superimposed image of the bands, and then extract one of the bands as your result. I hope these suggestions can help you. Of course, if you have any good solutions, I also hope you can tell me.Thanks!
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                史书
                            
                    
                        
                            
                                    474925155@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 10/6/2020 22:31，LP429<notifications@github.com> wrote： 




Hi, @qingshuiruoshan!

How is your work going? When I do this work like yours, the program has such a problem：

ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible

So do you have this situation and how did you solve it?

Thank you!!



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LP429** [comment]
@qingshuiruoshan Thanks for your advice! I will try it. If I have any way, I'll tell you. Thank you again.

**Comment by LP429** [comment]
你好，问题是否解决，我有一个问题想请问一下，怎么判断ＧＡＮ在训练中生成器和判别器达到平衡了呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qingshuiruoshan"<notifications@github.com&gt;; 
发送时间: 2020年10月6日(星期二) 晚上11:47
收件人: "JiahuiYu/generative_inpainting"<generative_inpainting@noreply.github.com&gt;; 
抄送: "梁鹏"<857682797@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [JiahuiYu/generative_inpainting] how to train single channel images? like[256, 256, 1] (#359)





 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         Hi,
         I haven't solved this problem yet. But maybe you can refer to the following two ways: the first is &nbsp;that you can refer to&nbsp;https://github.com/konstantg/dem-fill. Second, you can train the superimposed image of the bands, and then extract one of the bands as your result. I hope these suggestions can help you. Of course, if you have any good solutions, I also hope you can tell me.Thanks!
     
         
             
         
     
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 史书
                             
                     
                         
                             
                                     474925155@qq.com
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     On 10/6/2020 22:31，LP429<notifications@github.com&gt; wrote： 
 
 
 
 
 Hi, @qingshuiruoshan!
 
 How is your work going? When I do this work like yours, the program has such a problem：
 
 ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible
 
 So do you have this situation and how did you solve it?
 
 Thank you!!
 
 
 
 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by qingshuiruoshan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        你好，很抱歉现在才回答你的问题，你所想了解的问题我记得在github上Issues中有作者相应的回答，你可以从里面获取到相应的答案~
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                史书
                            
                    
                        
                            
                                    474925155@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 12/24/2020 16:07，LP429<notifications@github.com> wrote： 




你好，问题是否解决，我有一个问题想请问一下，怎么判断ＧＡＮ在训练中生成器和判别器达到平衡了呢



















------------------&nbsp;原始邮件&nbsp;------------------



发件人: "qingshuiruoshan"<notifications@github.com&gt;; 



发送时间: 2020年10月6日(星期二) 晚上11:47



收件人: "JiahuiYu/generative_inpainting"<generative_inpainting@noreply.github.com&gt;; 



抄送: "梁鹏"<857682797@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 



主题: Re: [JiahuiYu/generative_inpainting] how to train single channel images? like[256, 256, 1] (#359)























 



 



      



 



 



 



     font{ 



         line-height: 1.6; 



     } 



     ul,ol{ 



         padding-left: 20px; 



         list-style-position: inside; 



     } 



 



 



     



     



         Hi,



         I haven't solved this problem yet. But maybe you can refer to the following two ways: the first is &nbsp;that you can refer to&nbsp;https://github.com/konstantg/dem-fill. Second, you can train the superimposed image of the bands, and then extract one of the bands as your result. I hope these suggestions can help you. Of course, if you have any good solutions, I also hope you can tell me.Thanks!



     



         



             



         



     



     



      



     



         



                     



             



                 



                     



                             



                                 



                             



                             



                                 史书



                             



                     



                         



                             



                                     474925155@qq.com



                             



                         



                 



             



         



         



     



     



         签名由



         网易邮箱大师



         定制



     



  



 



     On 10/6/2020 22:31，LP429<notifications@github.com&gt; wrote： 



 



 



 



 



 Hi, @qingshuiruoshan!



 



 How is your work going? When I do this work like yours, the program has such a problem：



 



 ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible



 



 So do you have this situation and how did you solve it?



 



 Thank you!!



 



 



 



 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 



—



You are receiving this because you commented.



Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LP429** [comment]
好的，谢谢您，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiahuiYu/generative_inpainting"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 晚上10:32
收件人:&nbsp;"JiahuiYu/generative_inpainting"<generative_inpainting@noreply.github.com&gt;;
抄送:&nbsp;"梁鹏"<857682797@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JiahuiYu/generative_inpainting] how to train single channel images? like[256, 256, 1] (#359)





 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     
         
             
         
     
     
         你好，很抱歉现在才回答你的问题，你所想了解的问题我记得在github上Issues中有作者相应的回答，你可以从里面获取到相应的答案~
         
     
      
     
         
                     
             
                 
                     
                             
                                 
                             
                             
                                 史书
                             
                     
                         
                             
                                     474925155@qq.com
                             
                         
                 
             
         
         
     
     
         签名由
         网易邮箱大师
         定制
     
  
 
     On 12/24/2020 16:07，LP429<notifications@github.com&gt; wrote： 
 
 
 
 
 你好，问题是否解决，我有一个问题想请问一下，怎么判断ＧＡＮ在训练中生成器和判别器达到平衡了呢
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 
 
 
 发件人: "qingshuiruoshan"<notifications@github.com&amp;gt;; 
 
 
 
 发送时间: 2020年10月6日(星期二) 晚上11:47
 
 
 
 收件人: "JiahuiYu/generative_inpainting"<generative_inpainting@noreply.github.com&amp;gt;; 
 
 
 
 抄送: "梁鹏"<857682797@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;; 
 
 
 
 主题: Re: [JiahuiYu/generative_inpainting] how to train single channel images? like[256, 256, 1] (#359)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  
 
 
 
  
 
 
 
       
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
      font{ 
 
 
 
          line-height: 1.6; 
 
 
 
      } 
 
 
 
      ul,ol{ 
 
 
 
          padding-left: 20px; 
 
 
 
          list-style-position: inside; 
 
 
 
      } 
 
 
 
  
 
 
 
  
 
 
 
      
 
 
 
      
 
 
 
          Hi,
 
 
 
          I haven't solved this problem yet. But maybe you can refer to the following two ways: the first is &amp;nbsp;that you can refer to&amp;nbsp;https://github.com/konstantg/dem-fill. Second, you can train the superimposed image of the bands, and then extract one of the bands as your result. I hope these suggestions can help you. Of course, if you have any good solutions, I also hope you can tell me.Thanks!
 
 
 
      
 
 
 
          
 
 
 
              
 
 
 
          
 
 
 
      
 
 
 
      
 
 
 
       
 
 
 
      
 
 
 
          
 
 
 
                      
 
 
 
              
 
 
 
                  
 
 
 
                      
 
 
 
                              
 
 
 
                                  
 
 
 
                              
 
 
 
                              
 
 
 
                                  史书
 
 
 
                              
 
 
 
                      
 
 
 
                          
 
 
 
                              
 
 
 
                                      474925155@qq.com
 
 
 
                              
 
 
 
                          
 
 
 
                  
 
 
 
              
 
 
 
          
 
 
 
          
 
 
 
      
 
 
 
      
 
 
 
          签名由
 
 
 
          网易邮箱大师
 
 
 
          定制
 
 
 
      
 
 
 
   
 
 
 
  
 
 
 
      On 10/6/2020 22:31，LP429<notifications@github.com&amp;gt; wrote： 
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
  Hi, @qingshuiruoshan!
 
 
 
  
 
 
 
  How is your work going? When I do this work like yours, the program has such a problem：
 
 
 
  
 
 
 
  ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible
 
 
 
  
 
 
 
  So do you have this situation and how did you solve it?
 
 
 
  
 
 
 
  Thank you!!
 
 
 
  
 
 
 
  
 
 
 
  
 
 
 
  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 
 
 —
 
 
 
 You are receiving this because you commented.
 
 
 
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 
 
 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
