### ISSUE TITLE
conv2d() got an unexpected keyword argument 'dilations'

### ISSUE THREAD

**Issue by KANGCLOUD** [JiahuiYu/generative_inpainting#367]
Firstly, thanks for the sharing the code.
when i run the train.py,it has a problem that TypeError: conv2d() got an unexpected keyword argument 'dilations' in the inpaint_ops.py.

It would be very nice if any hints or suggestion.
Thanks in advanced.

**Comment by JiahuiYu** [comment]
@KANGCLOUD I don't know either. Since:

1. Our inpaint_ops.py does not have any 'dilations' argument.

2. Many other people can run this code successfully.

I would suggest to:

1. Clean your environment by creating a new virtual environment

2. Re-install or clone our repo, both generative_inpainting and tensorgym.

https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_ops.py

**Comment by KANGCLOUD** [comment]
thanks for your reply

---Original---
