### ISSUE TITLE
about the contextual attention

### ISSUE THREAD

**Issue by lipanpeng** [JiahuiYu/generative_inpainting#39]
In the code of contextual attention, foreground is x, background also x. I'm confused what's the sense to match x with x. Can you help me?

**Comment by JiahuiYu** [comment]
First thanks for your help on issue #38.

You can imagine that part of x is hallucinated (foreground), while another part of x is transformed from input image (background). We try to find if the hallucinated part of x have similar patches in background patch in space x, thus directly copy and paste to utilize long-range dependencies for better visual quality . The space x is learned by a neural network. One example is that if you mask one eye, most likely the filled result will be very similar to another eye in face. Other deep image inpainting systems usually fail in this case because they can not handle long-range dependencies spatially.

The attention module is with same merits with traditional image inpainting methods like [PatchMatch: A randomized correspondence algorithm for structural image editing](https://scholar.google.com/scholar?cluster=5178322014558641754&hl=en&as_sdt=2005&sciodt=0,5).

**Comment by 1900zyh** [comment]
@JiahuiYu Thank you for your work first. I have a confusion that, if you compute similarity by convoluting x on x directly, then you will find the most similarity patch of missing region is just the missing one, right? It seems that the operation in the attention layer part of your code is not the exactly one in your paper.
