### ISSUE TITLE
Tips to improve performance

### ISSUE THREAD

**Issue by dragen1860** [JiahuiYu/generative_inpainting#431]
Dear author: 
  Thanks for your insightful work again!
   May I ask you for some tips. I am working the this project and want to boost the performance. It's not a research project, hence a lot of trivial approach can be taken into consideration.
   I noticed that both the G and D network is rather small (~20MB) ， Have  you tried  larger models? does it help?
   besides, I converted the contextual attention module to a rather simply self attention module, since self-attention module is relatively easy to work on embedded devices. Does the self attention harm the performance? did I have other better replacement?
  Thank you for you help.

**Comment by JiahuiYu** [comment]
Large model does help at the cost of slower training speed and higher memory usage.

Contextual attention is important and is different to self-attention. I tried non-local attention before and it has much worse results. It is likely due to the fact that non-local/self attention does not have normalization or score fusing.
