### ISSUE TITLE
How to get the mask image during the test?

### ISSUE THREAD

**Issue by Liyao520** [JiahuiYu/generative_inpainting#481]
![图片](https://user-images.githubusercontent.com/61584515/99362337-52b73d00-28ee-11eb-88cb-1159a67f0239.png)

**Comment by ToBeOrNotTo** [comment]
Do you know how to get the mask image from input image now?

**Comment by JiahuiYu** [comment]
You can just produce by using numpy?

**Comment by ToBeOrNotTo** [comment]
sorry,maybe i didn't describe this issue. if i have a mask image like case1_input.png,so how can i get a image like case1_mask.png.
because i have some mask image like case1_input.png, i tried to get a image like case1_mask.png,but i can't get a good reslut.

**Comment by ToBeOrNotTo** [comment]
sorry,maybe i didn't describe this issue. if i have a mask image like case1_input.png,so how can i get a image like case1_mask.png.
because i have some mask image like case1_input.png, i tried to get a image like case1_mask.png,  but i can't get a good reslut.
![001_output](https://user-images.githubusercontent.com/27957725/100320792-afa4a880-2ffc-11eb-9c4d-da6da8adb822.png)

**Comment by ToBeOrNotTo** [comment]
sorry,maybe i didn't describe this issue. if i have a mask image like case1_input.png,so how can i get a image like case1_mask.png.
because i have some mask image like case1_input.png, i tried to get a image like case1_mask.png, but i can't get a good reslut.
![001_output](https://user-images.githubusercontent.com/27957725/100321088-22158880-2ffd-11eb-92f3-48b5b711b6d4.png)
